=== scibian/slurm-web/schema/racks.dtd
<!ELEMENT rackmap (nodetypes,racks)>

<!ELEMENT nodetypes (nodetype+)>

<!ELEMENT nodetype EMPTY>
<!ATTLIST nodetype id ID #REQUIRED>
<!ATTLIST nodetype model CDATA #REQUIRED>
<!ATTLIST nodetype height CDATA #REQUIRED>
<!ATTLIST nodetype width CDATA #REQUIRED>

<!ELEMENT racks (racksrow+)>
<!ATTLIST racks posx CDATA #IMPLIED>
<!ATTLIST racks posy CDATA #IMPLIED>
<!ATTLIST racks width CDATA #IMPLIED>
<!ATTLIST racks depth CDATA #IMPLIED>
<!ATTLIST racks rackwidth CDATA #IMPLIED>

<!ELEMENT racksrow (rack+)>
<!ATTLIST racksrow posx CDATA #IMPLIED>

<!ELEMENT rack (nodes)>
<!ATTLIST rack id ID #REQUIRED>
<!ATTLIST rack posy CDATA #IMPLIED>

<!ELEMENT nodes (node|nodeset)*>

<!ELEMENT node EMPTY>
<!ATTLIST node id ID #REQUIRED>
<!ATTLIST node type IDREF #REQUIRED>
<!ATTLIST node posx CDATA #IMPLIED>
<!ATTLIST node posy CDATA #IMPLIED>

<!ELEMENT nodeset EMPTY>
<!ATTLIST nodeset id ID #REQUIRED>
<!ATTLIST nodeset type IDREF #REQUIRED>
<!ATTLIST nodeset posx CDATA #IMPLIED>
<!ATTLIST nodeset posy CDATA #IMPLIED>
<!ATTLIST nodeset draw (up|down) "up">

=== scibian/slurm-web/conf/racks.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE rackmap SYSTEM "/usr/share/slurm-web/restapi/schema/dtd/racks.dtd">
<rackmap>

  <!--
    This file is an example of XML rackmap file for slurm-web.

    You must adapt it (or write one from scratch) to fit the racks composition
    of your own HPC cluster.

    First define your node types with their model name and dimensions. Then,
    define your racks with their positions and their nodes. You do not need to
    specify the position of all nodes. Specify the positions of the nodes in
    the 1st row + the position of the first node in the 2nd row. Then, the
    backend program is able to compute the positions of all other nodes (in
    nodesets) based on these initial positions.
  -->

  <nodetypes>
    <nodetype id="m32x4321"
              model="Vendor A 32 x4321"
              height="1"
              width="0.5"
              />
    <nodetype id="b43"
              model="Vendor B 43"
              height="2"
              width="1"
              />
  </nodetypes>


  <racks posx="0" posy="0" width="500" depth="300" rackwidth="1">
    <racksrow posx="0">
      <!-- Rack A1 -->
      <rack id="A1" posy="0">
        <nodes>
          <nodeset id="cn[001-036]"
                   type="m32x4321"
                   posx="0"
                   posy="3" />

          <nodeset id="cn[037-072]"
                   type="m32x4321"
                   posx="0"
                   posy="23" />
        </nodes>
      </rack>

      <!-- Rack A2 -->
      <rack id="A2" posy="1">
        <nodes>
          <nodeset id="cn[500-506],cn900"
                   type="m32x4321"
                   posx="0"
                   posy="42"
                   draw="down" />
          <node id="cn800"
                type="m32x4321"
                posx="0"
                posy="1" />
          <node id="cn801"
                type="b43"
                posx="0"
                posy="3" />
        </nodes>
      </rack>

      <!-- Rack A3 -->
      <rack id="A3" posy="2">
        <nodes>
          <nodeset id="cn[505-518]"
                   type="m32x4321"
                   posx="0"
                   posy="2" />

          <nodeset id="cn[519-536]"
                   type="m32x4321"
                   posx="0"
                   posy="10" />

          <nodeset id="cn[537-572]"
                   type="m32x4321"
                   posx="0"
                   posy="23" />
        </nodes>
      </rack>
    </racksrow>
  </racks>

</rackmap>

=== scibian/slurm-web/schema/example.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE rackmap SYSTEM "/usr/share/slurm-web/restapi/schema/dtd/racks.dtd">
<rackmap>

  <nodetypes>
    <nodetype id="m32x4321" model="Vendor A 32 x4321" height="1" width="0.5" />
    <nodetype id="b43" model="Vendor B 43" height="2" width="1" />
  </nodetypes>

  <racks posx="0" posy="0" width="500" depth="300">
    <racksrow>
      <rack id="rack1-1" posx="0" posy="0">
        <nodes>
          <node id="cn001" type="m32x4321" posx="0" posy="3" />
          <node id="cn002" type="m32x4321" posx="0.5" posy="3" />
          <node id="cn003" type="m32x4321" posx="0" posy="4" />

          <nodeset id="cn[004-072]" type="m32x4321" />
        </nodes>
      </rack>

      <rack id="rack1-2" posx="1">
        <nodes>
          <node id="cn101" type="m32x4321" posx="0" posy="3" />
          <nodeset id="cn[102-121]" type="m32x4321" posy="5" />
        </nodes>
      </rack>
    </racksrow>

    <racksrow>
      <rack id="rack2-1" posx="0" posy="0">
        <nodes>
          <node id="cn201" type="m32x4321" posx="0" posy="3" />
          <node id="cn202" type="m32x4321" posx="0.5" posy="3" />
          <node id="cn203" type="m32x4321" posx="0" posy="4" />

          <nodeset id="cn[204-272]" type="m32x4321" />
        </nodes>
      </rack>

      <rack id="rack2-2" posx="1">
        <nodes>
          <node id="cn301" type="m32x4321" posx="0" posy="3" />
          <nodeset id="cn[302-321]" type="m32x4321" posy="5" />
        </nodes>
      </rack>
    </racksrow>
  </racks>
</rackmap>
